<a href="https://colab.research.google.com/github/amaziarczyk/Projects/blob/master/Pozosta%C5%82e_projekty/PCA_Analiza_g%C5%82%C3%B3wnych_sk%C5%82adowych_i_t_SNE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objs as go
import sklearn

In [ ]:
#Wczytanie danych
df2=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nauka/PCA/wine.data', header=None)
df=df2.copy()
df.head()

0      1     2     3     4    5   ...    8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735

[5 rows x 14 columns]

In [ ]:
dane = df.iloc[:,1:]
target= df.iloc[:,0]

In [ ]:
dane[:3]

1     2     3     4    5     6     7     8     9     10    11    12    13
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92  1065
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40  1050
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17  1185

In [ ]:
target[:3]

0    1
1    1
2    1
Name: 0, dtype: int64

In [ ]:
target.value_counts()

2    71
1    59
3    48
Name: 0, dtype: int64

In [ ]:
#Podział na zbiór treningowy i testowy
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dane, target)
print("Ilość danych train:", X_train.shape[0])
print("Ilość danych test:",X_test.shape[0])

Ilość danych train: 133
Ilość danych test: 45


In [ ]:
# Standaryzacja danych treingowych
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
X_train_s=scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

In [ ]:
X_train_s[:3]

array([[ 1.03968719, -0.41820823,  1.57448363,  0.00180101,  0.57531181,
         1.01987834,  0.88333757,  0.07051401,  0.27513355, -0.2448539 ,
         1.23012538,  1.10627865,  0.50926482],
       [-0.71296731, -0.68117353, -0.61580884,  0.92999465,  0.65159942,
        -0.49045486,  0.0194132 , -0.16791895,  0.01499543, -1.30615999,
         0.4095872 ,  0.48312506, -1.23664782],
       [ 0.88255265, -0.62676691, -0.40037024, -0.8964509 ,  1.41447549,
         0.4634398 ,  0.81461632, -1.2011284 ,  0.03233797,  0.34234415,
        -0.19501988,  0.82302702,  0.9534005 ]])

In [ ]:
# PCA
from sklearn.decomposition import PCA

In [ ]:
pca=PCA(n_components=3)
X_train_p=pca.fit_transform(X_train_s)
X_test_p = pca.transform(X_test_s)

In [ ]:
X_train_p[:3]

array([[ 2.17985816,  0.52286136,  1.28864433],
       [-0.33235155, -1.8294327 ,  0.50433021],
       [ 2.1939836 ,  0.73975793, -1.15229722]])

In [ ]:
df_pca=pd.DataFrame(data=np.c_[X_train_p, y_train], columns=[1,2,3,'target'])
df_pca.head()

1         2         3  target
0  2.179858  0.522861  1.288644     1.0
1 -0.332352 -1.829433  0.504330     2.0
2  2.193984  0.739758 -1.152297     1.0
3 -1.775903 -0.779595  3.290033     2.0
4 -1.110118 -2.393979 -1.595251     2.0

In [ ]:
px.scatter_3d(df_pca,
           x=1,
           y=2,
           z=3,
           color='target', width= 700, height=500)

In [ ]:
# wyjaśniona wariancja
a= pca.explained_variance_
a

array([4.77476112, 2.54840147, 1.47482182])

In [ ]:
# wartości skumulowane 
b=(pca.explained_variance_).cumsum()
b

array([4.77476112, 7.32316259, 8.79798441])

In [ ]:
df_var=pd.DataFrame(data=[a,b])
df_var=df_var.T
df_var.columns=['wyjaśniona wariancja','skumulowane']
df_var['index']=df_var.index+1
df_var

wyjaśniona wariancja  skumulowane  index
0              4.774761     4.774761      1
1              2.548401     7.323163      2
2              1.474822     8.797984      3

In [ ]:
fig= go.Figure(data=[go.Bar(x=df_var['index'], y=df_var['wyjaśniona wariancja']),
                     go.Scatter(x=df_var['index'], y=df_var['skumulowane'])])
fig.show()
                            

In [ ]:
# wyjaśnione zostało 79% wariancji

T-SNE

In [ ]:
df.head()

0      1     2     3     4    5   ...    8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735

[5 rows x 14 columns]

In [ ]:
# Standaryzacja 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std=scaler.fit_transform(X_train)

In [ ]:
from sklearn.manifold import TSNE

In [ ]:
sne =TSNE(n_components =3)
X_train_sne= sne.fit_transform(X_train_std)

In [ ]:
df_sne=pd.DataFrame(data=np.c_[X_train_sne, y_train])
df_sne.head()

0           1           2    3
0    1.186703   94.533318 -123.049049  1.0
1  105.072395 -137.420090  -56.105854  2.0
2   79.562943  120.183525  -13.444576  1.0
3  -43.595394  -88.832672   -1.951110  2.0
4  -41.382019  -87.237106  -76.574532  2.0

In [ ]:
px.scatter_3d(df_sne,x=0, y=1, z=2, color=3, width= 700, height=500 )

Porównanie PCA i t-SNE

In [ ]:
df_p=df.copy()
df_p.head()

0      1     2     3     4    5   ...    8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735

[5 rows x 14 columns]

In [ ]:
# porównanie dla 2
# PCA
p=PCA(n_components=2)
X_train_pp=p.fit_transform(X_train_s)
X_test_pp = p.transform(X_test_s)

# t-SNE
t=TSNE(n_components=2)
X_train_tt=t.fit_transform(X_train_s)


In [ ]:
df_p2=pd.DataFrame(data=np.c_[X_train_pp,X_train_tt,y_train], columns=['pp_0','pp_1', 'tt_0','tt_1','target'])
df_p2.head()

pp_0      pp_1      tt_0      tt_1  target
0  2.179858  0.522861  5.063641 -5.375824     1.0
1 -0.332352 -1.829433  3.342239  1.737666     2.0
2  2.193984  0.739758  6.203441 -7.607771     1.0
3 -1.775903 -0.779595  1.164444  1.995310     2.0
4 -1.110118 -2.393979  5.100893  3.493160     2.0

In [ ]:
# Wykres porównanie PCA i t_SNE

px.scatter(df_p2, x='pp_0', y='pp_1', color='target', width= 700, height= 400, title= "PCA")

In [ ]:
px.scatter(df_p2, x='tt_0', y='tt_1', color='target', width= 700, height= 400, title="TSNE")