<a href="https://colab.research.google.com/github/amaziarczyk/Projects/blob/master/Pozosta%C5%82e_projekty/PCA_Analiza_g%C5%82%C3%B3wnych_sk%C5%82adowych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objs as go
import sklearn

In [5]:
#Wczytanie danych
df2=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nauka/PCA/wine.data', header=None)
df=df2.copy()
df.head()

0      1     2     3     4    5   ...    8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735

[5 rows x 14 columns]

In [9]:
dane = df.iloc[:,1:]
target= df.iloc[:,0]

In [11]:
dane[:3]

1     2     3     4    5     6     7     8     9     10    11    12    13
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92  1065
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40  1050
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17  1185

In [12]:
target[:3]

0    1
1    1
2    1
Name: 0, dtype: int64

In [13]:
target.value_counts()

2    71
1    59
3    48
Name: 0, dtype: int64

In [14]:
#Podział na zbiór treningowy i testowy
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(dane, target)
print("Ilość danych train:", X_train.shape[0])
print("Ilość danych test:",X_test.shape[0])

Ilość danych train: 133
Ilość danych test: 45


In [21]:
# Standaryzacja danych treingowych
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
X_train_s=scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

In [24]:
X_train_s[:3]

array([[ 1.03968719, -0.41820823,  1.57448363,  0.00180101,  0.57531181,
         1.01987834,  0.88333757,  0.07051401,  0.27513355, -0.2448539 ,
         1.23012538,  1.10627865,  0.50926482],
       [-0.71296731, -0.68117353, -0.61580884,  0.92999465,  0.65159942,
        -0.49045486,  0.0194132 , -0.16791895,  0.01499543, -1.30615999,
         0.4095872 ,  0.48312506, -1.23664782],
       [ 0.88255265, -0.62676691, -0.40037024, -0.8964509 ,  1.41447549,
         0.4634398 ,  0.81461632, -1.2011284 ,  0.03233797,  0.34234415,
        -0.19501988,  0.82302702,  0.9534005 ]])

In [25]:
# PCA
from sklearn.decomposition import PCA

In [27]:
pca=PCA(n_components=3)
X_train_p=pca.fit_transform(X_train_s)
X_test_p = pca.transform(X_test_s)

In [28]:
X_train_p[:3]

array([[ 2.17985816,  0.52286136,  1.28864433],
       [-0.33235155, -1.8294327 ,  0.50433021],
       [ 2.1939836 ,  0.73975793, -1.15229722]])

In [45]:
df_pca=pd.DataFrame(data=np.c_[X_train_p, y_train], columns=[1,2,3,'target'])
df_pca.head()

1         2         3  target
0  2.179858  0.522861  1.288644     1.0
1 -0.332352 -1.829433  0.504330     2.0
2  2.193984  0.739758 -1.152297     1.0
3 -1.775903 -0.779595  3.290033     2.0
4 -1.110118 -2.393979 -1.595251     2.0

In [54]:
px.scatter_3d(df_pca,
           x=1,
           y=2,
           z=3,
           color='target', width= 700, height=500)

In [33]:
# wyjaśniona wariancja
a= pca.explained_variance_
a

array([4.77476112, 2.54840147, 1.47482182])

In [34]:
# wartości skumulowane 
b=(pca.explained_variance_).cumsum()
b

array([4.77476112, 7.32316259, 8.79798441])

In [57]:
df_var=pd.DataFrame(data=[a,b])
df_var=df_var.T
df_var.columns=['wyjaśniona wariancja','skumulowane']
df_var['index']=df_var.index+1
df_var

wyjaśniona wariancja  skumulowane  index
0              4.774761     4.774761      1
1              2.548401     7.323163      2
2              1.474822     8.797984      3

In [65]:
fig= go.Figure(data=[go.Bar(x=df_var['index'], y=df_var['wyjaśniona wariancja']),
                     go.Scatter(x=df_var['index'], y=df_var['skumulowane'])])
fig.show()
                            

In [ ]:
# wyjaśnione zostało 79% wariancji